set_vague_goal:
  description: >
    User sets a vague goal. Ari delegates to Milo. Milo defines SMART structure. Zara stores data. Nico breaks it into subtasks. Clara schedules milestones. Felix sets habit reminders.
  expected_output: >
    A structured SMART goal, milestones, scheduled events, and habit reminders for the user.
  agent: ari

user_blocked:
  description: >
    User feels blocked. Ari delegates to Otto. Otto reframes issue. Refers to Nova for new learning. Nova finds resource. Felix tracks new routine.
  expected_output: >
    Reframed perspective, learning resource, and a new tracked routine for the user.
  agent: ari

quarterly_review:
  description: >
    Ari compiles data from Zara, Clara, Felix. Presents insight report with motivational message from Otto.
  expected_output: >
    A quarterly review report with insights and a motivational message.
  agent: ari

calendar_conflict:
  description: >
    Calendar conflict detected. Clara triggers realignment. Notifies Nico to adjust project timeline. Ari relays to user.
  expected_output: >
    Adjusted project timeline and user notification about the realignment.
  agent: ari
